version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=pg_pw
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '5000:5000'
    environment:
      - PGUSER=postgres
      - PGHOST=localhost
      - PGDATABASE=flask_cookiecutter
      - PGPASSWORD=pg_pw
      - PGPORT=5432